package com.example.myapplication.util;

import android.content.Context;

import com.example.myapplication.model.dataFood;
import com.example.myapplication.view.DB;

import java.util.ArrayList;
import java.util.List;

public class putFood {
    private Context context;

    public putFood(Context context) {
        this.context = context;
        DB db = new DB(context);
        db.open();
        if (db.checkCountFood() <= 0) {
            db.insertFD("Cá hồ Núi Cốc","Đến với hồ Núi Cốc, du khách không chỉ bị cuốn hút bởi vẻ đẹp sơn thủy hữu tình của một vùng lòng hồ mênh mông sông nước, đắm say với câu chuyện tình huyền thoại nàng Công, chàng Cốc mà còn bởi những ẩm thực nổi tiếng như: dê núi, gà đồi, cá sông, lợn mán, dúi rừng…Trong đó, không thể không kể đến hai món cá mang hương vị riêng chỉ có ở hồ Núi Cốc: Đó là món cá sông và cá trắm đen.","Cá sông là loại cá nhỏ chỉ bằng ngón tay trỏ. Mặc dù loại cá này sống trong lòng hồ Núi Cốc nhưng người dân địa phương vẫn quen gọi là cá sông. Loại cá này có thể chế biến thành các món: món cá chiên giòn hoặc có thể kho tương; hoặc nấu với măng rừng. Tuy nhiên, cách mà nhiều người thích thưởng thức hơn cả vẫn là cá chiên giòn, cuộn với lá lốt chấm nước mắm tỏi hoặc nước tương gừng.\n" +
                    "Một trong những món cá cũng được du khách ưa thích mỗi khi đến với hồ Núi Cốc chính là món cá trắm đen. Loại cá này ăn lúc ngon nhất phải có cân nặng khoảng 6 đến 7 kg. Cá trắm đen có thể chế biến được khá nhiều món: cá hấp bia; cá om dưa trên bếp cồn; sốt ngũ liễu… Những con to có thể xẻ thịt ra làm món cá chiên vừng, nướng than hoa. Đầu và đuôi cá nấu cháo đỗ xanh hoặc canh măng dọc mùng rất bổ dưỡng.Tuy nhiên, món ngon nhất vẫn là cá hấp bia. Để làm món này không khó: Trước tiên rửa cá sạch; bóc mang cho khỏi tanh, rồi mổ bóc sạch ruột. Lấy khăn mặt sạch (đã tẩm nước muối hoặc dấm) lau khô để cá không tanh, hết chất nhớt trong bụng. Chuẩn bị gia vị gồm có: gừng ta, hành, nghệ, rau răm, sả, thì là. Khi cá sơ chế xong thì ướp một phần các gia vị trên vào cá và nêm thêm chút nước mắm, mì chính, hạt nêm đều trên mặt cá; một phần ướp vào bụng cá.Tiếp theo rót một chút tương bần lên mình cá. Hấp cá có hai cách, có thể cho vào lồng hấp cách thủy hoặc hấp trực tiếp bằng chảo trên bếp ga. Nếu hấp trên chảo, khi cá ướp xong đổ bia và một chút nước xâm xấp cá rồi đun lên 15 đến 20 phút. Khi thấy mình cá tẽ ra thì tiếp tục rót thêm bia lần thứ hai vào; phi hành khô rắc lên cá, cho thêm vài cọng hành tươi, vừa đẹp mắt vừa tăng thêm hương vị, sự hấp dẫn của món ăn.","ca_ho_nui_coc","ca_ho_nui_coc_2","ca_ho_nui_coc_3","honuicoc");
            db.insertFD("Bánh Nẳng của đồng bào Tày","Nếu có dịp về với mảnh đất Thủ đô gió ngàn – ATK Định Hóa, du khách sẽ bắt gặp những thức quà quê dân dã của bà con dân tộc Tày, Nùng nơi đây. Đó là những sản phẩm mang đặc trưng của núi rừng ATK Định Hóa như: Cơm lam, bánh nẳng, bánh chưng Tày, măng rừng, rau ngót rừng... Trong đó bánh nẳng là một trong những thức quà được nhiều du khách lựa chọn để mua về làm quà cho bạn bè, người thân.","Bánh nẳng (hay còn gọi là bánh tro) là một trong những loại bánh được người Tày rất yêu thích. Sở dĩ có tên gọi là bánh tro vì xuất phát từ phụ liệu làm bánh là nước tro được pha chế từ tro than thu được sau khi đốt cháy một số loại thảo mộc, dược liệu.\n" +
                    "Để bánh nẳng thơm ngon, lại đẹp thì công đoạn đốt tro, lọc tro cầu kỳ, công phu. Những loại cây thường được đốt lấy tro làm bánh là cây vừng, cây đa hoặc vỏ chuối. Và khâu lọc nước cũng lắm công phu. Khi lọc, phải cho vôi, lúc sôi sẽ nổi hết tạp chất lên trên, lọc bỏ, để gần nguội nước mới ngâm gạo được. Nhiều vôi bánh sẽ nồng, nhạt vôi quá thì bánh sẽ không nhừ, cho nhiều tro thì bánh thâm đen, ít tro thì bánh nhạt...Dung dịch nước vôi và tro phải trong, có màu vàng hổ phách mới đạt yêu cầu, sau đó cho gạo vào nước ngâm một đêm. Khi vớt gạo gói bánh cần xả với nước thật sạch, xóc với một chút muối, để ráo. Đây là công đoạn cốt yếu để tạo nên hương vị thanh mát của bánh.","banh_nang","banh_nang_2","banh_nang_3","atk");
            db.insertFD("Na La Hiên","Huyện Võ Nhai không chỉ được biết đến với các di tích lịch sử, danh lam thắng cảnh mà mảnh đất này còn được biết đến với nhiều sản vật trong đó có na - một loại trái cây đặc biệt được đất trời tặng riêng cho vùng đất La Hiên thuộc địa phận Võ Nhai\n" +
                    " \n" +
                    "\n" +
                    "Ở Thái Nguyên na được trồng tại nhiều địa phương, hầu như huyện nào người dân cũng trồng na nhưng chỉ có vùng đất La Hiên, Võ Nhai được coi là đất na. Bởi lẽ, na ở đây có được vị ngọt đậm, hương thơm khó quên không lẫn với bất cứ nơi nào. Na La Hiên quả to, múi căng, thưa hạt, bóc một lớp vỏ mỏng để lộ lớp cùi trắng ngần, bên trong là hạt nhỏ màu đen nháy, đưa vào miệng nếm thử có vị ngọt đậm đà, mùi hương cũng rất đặc trưng, đó không phải là một mùi thơm nức mũi mà nhẹ nhàng, dìu dịu, tinh khiết. Mùa na chín, thương lái từ khắp nơi tấp nập đổ về đây mua na tạo nên sự đông đúc, nhộn nhịp suốt dọc hai bên đường quốc lộ 1B, đoạn qua xã La Hiên. Cây na đã gắn bó với nguời dân nơi đây, nhiều gia đình trong xã thoát nghèo, làm giàu từ loại cây này.","Người dân ở đây ít khi phải mang na ra chợ bán, thường lái buôn đến tận nhà đặt mua, thậm chí có những nhà, lái buôn đến đặt mua cả vườn từ khi na còn chưa mở mắt. Na La Hiên vì thế mà theo chân thương lái đi về khắp các chợ lớn nhỏ trên địa bàn tỉnh Thái Nguyên, xuôi về Thủ đô ngàn năm văn hiến, ra Quảng Ninh, Hải Phòng, và nhiều tỉnh thành trên cả nước. ","na","na_2","na_3","hangphuonghoang");
            db.insertFD("Bánh Chưng Bờ Đậu","Sản phẩm bánh chưng Bờ Đậu  có từ những năm 1960. Tổ nghề làm bánh ở đây được người dân cho là cụ Nguyễn Thị Xuân, thường gọi là cụ Đấng (gọi theo tên của chồng). Cụ Đấng là người ở xã Củ Lũng. Dân làng kể lại, trước đây, quán bánh của cụ Đấng nằm gọn dưới gốc một cây phượng lớn ven đường, quán tuy nhỏ nhưng lúc nào cũng đông khách vì hương vị thơm ngon của bánh chưng do cụ Đấng làm. Đến lúc về già, cụ truyền lại nghề cho con cháu và bánh chưng Bờ Đậu được lưu truyền cho đến giờ.","Để làm nên một sản phẩm bánh chưng Bờ Đậu ngon thì khâu chọn nguyên liệu cũng hết sức quan trọng. Tất cả phải có nguồn gốc xuất xứ rõ ràng, được đảm bảo chất lượng an toàn thực phẩm. Gạo nếp để gói bánh thường được bà con dùng loại gạo nếp Vải của huyện Chợ Đồn, tỉnh Bắc Kạn  hoặc nếp cái hoa  vàng của tỉnh Hưng Yên. Năm nay, một số hộ gói bằng  giống gạo nếp Thầu Dầu, một sản phẩm nông nghiệp nổi tiếng của huyện Phú Bình, tỉnh Thái Nguyên. Đỗ làm nhân bánh được bà con chọn từ loại đậu xanh nguyên lõi, vỏ mỏng, vàng tươi và có vị thơm tự nhiên. Cùng với đó là thịt lợn ba chỉ tươi ngon, săn chắc, ướp với hạt tiêu Bắc và gói bằng lá dong xanh mướt, bản rộng được lấy từ núi rừng Việt Bắc. Điều đặc biệt ở làng nghề bánh chưng Bờ Đậu là nguồn nước dùng để luộc bánh phải được lấy từ dãy núi Cẩm nằm sát phía sau làng nghề Bờ Đậu. Nguồn nước ở đây được thiên nhiên ưu đãi và được người dân coi như “ nước giếng thần”. Bà Liên, trưởng làng nghề bánh chưng Bờ Đậu cho biết: “Chỉ khi luộc với nguồn nước này, bánh chưng Bờ Đậu mới thực sự bộc lộ hết hương vị thơm ngon, độc đáo riêng biệt mà không một loại bánh chưng nào có thể sánh được. ","banh_chung","banh_chung_2","banh_chung_3","denduom");
            db.insertFD("Nham - đặc sản đồng quê Phú Bình","Trong tiết trời se lạnh của mùa thu, nếu có dịp về với mảnh đất Hà Châu, Phú Bình du khách đừng quên thưởng thức món nham - một món ăn độc đáo mang đậm một bản sắc truyền thống trong văn hóa ẩm thực của người Hà Châu.\n" +
                    " \n" +
                    "Trám đen xưa nay vẫn là loại quả được nhân dân vùng Hà Châu ven sông Cầu gìn giữ như một đặc sản riêng của quê hương. Vào mùa trám chín, cuối tháng 7, đầu tháng 8 (âm lịch), người Hà Châu thường làm món ăn đặc sản truyền thống này.","Nguyên liệu để chế biến  món nham được làm từ 14 loại thực phẩm, gia vị dân dã gồm: Trám đen, cá cháy hoặc các mè trắng, củ chuối tiêu non, vừng, lạc, thịt ba chỉ, khế chua, lá gừng, lá sung, lá nhội, lá đinh lăng, cùi dừa, tương, dấm thanh… Chế biến món nham cũng thật công phu. Trám đen ỏm vừa chín tách hạt thái nhỏ, cá cháy bắt từ sông Cầu (hoặc cá mè trắng) rửa sạch lọc thịt, bỏ da, dùng giấy bản thấm kĩ; Nếu làm nham cá sống thì thịt cá thái chỉ. Nếu làm nham cá nướng thì cá mang nướng bằng than hoa (nướng 3 lửa, phơi 2 sương). Thịt ba chỉ thái miếng nhỏ, nướng chín thơm. Củ chuối thái nhỏ. Vừng, lạc rang thơm, giã nhỏ cùng với khế, lá sung, lá vừng non, lá nhội, cùi dừa thái thật nhỏ…  và bằng những bí quyết truyền lại từ xưa, người Hà Châu đã làm ra món nham rất thơm, ngon, béo, bùi với những hương vị đồng quê đặc biệt.\n" +
                    "Nham có thể ăn kèm với bánh đa hoặc bánh tráng. Một món ăn dân dã, nhưng lạ miệng, thơm ngon đủ vị, hấp dẫn du khách khi đến với vùng đất Phú Bình. ","nham","nham_2","nham_3","dinhphuongdo");
            db.insertFD("Quả cọ - ATK Định Hóa","Đến với ATK Định Hóa, du khách không chỉ đến với một vùng đất giàu truyền thống cách mạng mà vùng đất ấy còn níu bước chân người bởi những sản vật địa phương dân giã nhưng mang đậm hồn quê, trong đó không thể không nhắc đến cọ bùi.\n" +
                    " \n" +
                    "Từ bao đời, cây cọ đã gắn bó với vùng đất ATK Định Hóa. Hình ảnh những thân cọ vươn cao, xanh ngút tầm mắt là một nét cảnh quan đặc trưng của vùng chiến khu xưa. Rừng cọ đã trở thành một biểu tượng của sự gắn bó, đùm bọc, chở che bền chặt đến thiêng liêng. Không những vậy, cây cọ còn có giá trị tương đối lớn về mặt kinh tế. Tất cả các bộ phận từ cây cọ đều có thể tận dụng. Lá cọ dùng để lợp mái nhà tước lấy gân lá để bán, cuống lá dùng để chẻ nan dệt mành, hoặc thân cây cọ già có thể làm các đồ thủ công mỹ nghệ. Đặc biệt, quả cọ có vị bùi, ngậy là món quà dân dã hấp dẫn với nhiều khách du lịch mỗi khi đặt  chân đến mảnh đất này","Vào quãng giữa tháng 7 (âm lịch) hàng năm là những cây cọ trong rừng bắt đầu ra hoa, kết trái. Đến cuối tháng 10, đầu tháng 11 (âm lịch) là những trái cọ bắt đầu chín, màu vỏ xanh đậm rồi ngả sáng ra như màu xanh da trời. Lúc này chính là mùa thu hoạch cọ rừng. Cọ chín sau khi hái về, ngâm trong nước ấm nóng khoảng 50 - 60 độ, khoảng 10 phút sau là chín, cùi dầy vàng ươm, thơm một mùi hương thật khó tả, giống hệt một viên mỡ gà được vo tròn lẳn, dính vàng cả mười đầu ngón tay, mỗi năm mới được ăn một lần.\n" +
                    "\n" +
                    "Quả cọ được hái về rửa sạch bụi đất, đem xóc lẫn với những mảnh cật nứa già cho bong vỏ xanh sau đó mang đi ỏm. Nước ỏm quả cọ phải được đun bằng nước giếng khơi hay nước nguồn, khi nước nóng già nổi bọt lăn tăn, thì cho quả cọ vào ỏm, đến khi bóp thấy cọ mềm, nước váng nổi vàng sóng sánh như mỡ gà là có thể ăn được rồi, cọ ỏm có lớp vỏ mỏng màu nâu sẫm, lõi cọ màu vàng, càng dầy càng ngon. Khi ỏm cọ phải chú ý thời gian cho phù hợp với độ sôi của nước, nếu không khéo cọ sẽ bị tóp lại, cứng chát không ăn được. Thế nên ỏm được một mẻ cọ ngon là phải khéo léo, kì công. Người ăn cọ sành là người biết chọn cho mình những quả cọ tròn, cùi dầy có màu vàng như mật ong, khi nhấm nháp còn thấy dẻo, dính ở răng thì đó chính là loài cọ nếp quý. Cọ ỏm chấm với nước mắm là ngon nhất thế nhưng tùy thuộc khẩu vị từng người có thể thay bằng bột canh hay tương ớt.","co","co_2","co_3","atk");
            db.insertFD("Chè Tân Cương","Đặc sản hàng đầu của Thái Nguyên phải nói ngay đến là trà, bởi trà Thái đượm đà vị chát dịu, để lại dư vị ngọt ngào và thoảng hương thơm mùi cốm, khiến cho ai mới nhấp môi cũng sẽ còn nhớ mãi.\n" +
                    "\n" +
                    "Nhà thơ Dương Thuấn cũng đã phải thốt lên trong bài thơ Trà Thái Nguyên:\n" +
                    "\n" +
                    "“Trà Nhật, trà Tầu, trà năm châu bốn bể\n" +
                    "\n" +
                    "Uống bao thứ trà của nghìn muôn sứ sở\n" +
                    "\n" +
                    "Chẳng đâu ngon thơm như trà Thái Nguyên”","Nhờ thổ nhưỡng và khí hậu thích hợp, nên đâu đâu trên miền đất Thái Nguyên cây chè cũng được phát triển tốt tươi, đã có những vùng chè nổi tiếng như chè La Bằng (Đại Từ); chè Khe Cốc (Phú Lương); chè Trại Cài (Đồng Hỷ) nhưng nổi tiếng hơn cả là chè Tân Cương (T.P Thái Nguyên). Du khách qua đây đều nói “Đến Thái Nguyên mà chưa được thưởng thức một chén trà Tân Cương vào buổi sớm mai, hay chưa mua được vài lạng chè móc câu xao suốt mang về thì chưa thể gọi là đã đến Thái Nguyên”!...","che","che_2","che_3","honuicoc");
            db.insertFD("Bánh trứng kiến – đặc sản Định Hóa","Bánh trứng kiến, tiếng Tày gọi là “pẻng rày”, món ăn dân dã nhưng được chế biến tương đối cầu kì với vị thơm ngon riêng không lẫn với hương vị của bất cứ món bánh nào đã trở thành một trong những nét văn hóa ẩm thực độc đáo của đồng bào dân tộc Tày vùng Định Hóa, Thái Nguyên nói riêng và vùng núi phía Bắc nói chung.\n" +
                    "Đúng như tên gọi của nó, trứng kiến là một trong những nguyên liệu quan trọng để làm nên món bánh này. Ngoài ra còn có bột gạo nếp, thịt lợn băm nhỏ, hành khô, vừng, lá vả. Hàng năm, cứ vào dịp tháng  4, tháng 5, bà con dân tộc Tày lại vào rừng để lấy trứng kiến mang về làm bánh và chỉ lấy trứng của loại kiến đen có thân nhỏ, đuôi nhọn mà người Tày thường gọi là \"tua rày\". Loại kiến này thường làm tổ trên cây vầu, cây găng, cây xoan…\n" +
                    "Một tổ kiến to có thể lấy được vài ba chén trứng. Trứng kiến có màu trắng sữa, to bằng hạt gạo, căng mọng. khi lấy về được nhặt, sẩy cẩn thận cho hết vỏ kiến, tạp chất, rửa sạch, để ráo. Sau đó, bắc một chiếc chảo lên bếp, phi thơm hành với mỡ, cho trứng kiến vào rang kỹ cùng với thịt ba chỉ băm nhỏ và một chút lá kiệu hay lá hẹ cho đến khi trứng và thịt chuyển màu vàng sậm, thơm lừng thì nhấc xuống để nguội rồi trộn đều với vừng hoặc lạc rang giã nhỏ để làm nhân bánh.  \n" +
                    "\n" +
                    "Phần vỏ bánh được làm từ bột gạo nếp. Bột có thể là bột khô hoặc bột ướt nhưng theo kinh nghiệm của người làm bánh thì bánh làm từ bột ướt sẽ mềm dẻo hơn, ngon hơn. Để bánh không dẻo dính quá, người ta thường trộn thêm một chút bột tẻ. Sau khi bột ráo nước, bột được nhào thật mịn cùng với một chút bột canh, mỳ chính.\n" +
                    "\n" +
                    "","Lá vả rửa sạch, bỏ phần gân lá ở mặt dưới rồi trải bột lên đó với độ dày vừa phải. Tiếp đến, rải đều trứng kiến lên trên lớp bột và gập đôi chiếc lá lại, người cẩn thận thì bọc thêm một lớp lá vả ở bên ngoài rồi dùng dây buộc lại, đem hấp cách thủy chừng 30 – 40 phút là chín. Khi bánh chín đem ra để nguội rồi dùng kéo cắt ra từng miếng vuông vừa phải, đẹp mắt.\n" +
                    "\n" +
                    " Bánh trứng kiến với hàm lượng dinh dưỡng cao, có thể ăn nóng hay nguội tùy ý, mỗi lúc đều có vị ngon riêng. Khi ăn bánh, người ta ăn cả phần lá vả. Bánh có vị thơm ngon rất lạ, vừa có độ dẻo, thơm của bột nếp lại có vị bùi của lá vả, đặc biệt là vị béo béo, ngậy ngậy của nhân bánh được làm từ trứng kiến. Một số người đã ăn bánh trứng kiến nhiều lần thường thích ăn những chiếc bánh mà nhân chỉ có trứng kiến với hành khô phi thơm, không trộn thêm các nguyên liệu khác. Tuy nhiên, theo bà Ma Thị Liên (Phú Đình, Định Hóa), việc trộn thêm thịt ba chỉ, lá kiệu, vừng, lạc… không chỉ vì ngày nay trứng kiến ngày một khan hiếm mà vì những nguyên liệu ấy còn góp phần làm cho chiếc bánh béo ngậy hơn, nhiều hương vị hơn và với những người có cơ địa dị ứng với một số loại ấu trùng như nhộng ong, nhộng tằm… thì khả năng bị dị ứng thấp hơn.\n" +
                    "Đến với Thái Nguyên, mảnh đất thủ đô gió ngàn, chiến khu Việt Bắc vào những ngày cuối xuân đầu hạ, du khách đừng quên thưởng thức món bánh kỳ lạ mà đầy thú vị, hấp dẫn này.","banh_kien","banh_kien_2","banh_kien_3","atk");
            db.insertFD("Cơm Lam - món ăn giản dị của núi rừng ATK","Cơm Lam là món ăn khá phổ biến của đồng bào dân tộc vùng núi. Đi làm nương, phát rẫy, vào rừng đốn cây… người ta cũng đốt cơm lam. Trong tiệc cưới, cơm Tết… ít khi thiếu những ống cơm lam.\n" +
                    "Gạo nếp nương, nếp cái ngâm kĩ đổ vào những ống tre tươi bánh tẻ rồi nút lá dong tươi, dựng nướng trong đống lửa củi nỏ. Khi vỏ các ống tre cháy xém, mùi thơm nếp hương tỏa lan là cơm lam đã chín. Chờ ống cơm lam bớt nóng, dùng dao sắc “vót” dần lớp ngoài ống tre; phải “vót” rất khéo để giữ lớp màng tre non. Cơm lam chín dẻo đượm một mùi thơm khó tả, chấm với muối lạc, muối vừng thơm phức… sẽ là món ẩm thực dân dã, một lần thưởng thức mãi không quên.","Bạn có thể ăn cơm lam kèm với các món ăn khác, tuy nhiên món cơm lam này ăn với muối riềng là tuyệt vời nhất. Muối riềng làm từ muối rang với củ riềng giã nhỏ như kiểu rang muối vừng, rất đơn giản mà lại ngon đến khỏ tả. Vị thơm cay của muối riềng quyện với vị ngọt mát của cơm làm tạo nên một hương vị thanh đạm đến lạ thường. Sáng tạo hơn, người ta chiên cơm lam cho chín vàng rồi ăn kèm với dừa tươi bảo nhỏ cũng rất ngon.","com_lam","com_lam_2","com_lam_3","atk");
            db.insertFD("Bánh Ngải","Giống như các dân tộc thiểu số khác ở Thái Nguyên, dân tộc Tày có một loại đặc sản riêng thường làm vào Tết Thanh minh, đó là bánh ngải. Bánh ngải có màu xanh đặc trưng của thiên nhiên, hình thù và cách làm gần giống với bánh dày của người miền xuôi.\n" +
                    "\n" +
                    " \n" +
                    "\n" +
                    "Để làm bánh ngải, người Tày chọn nếp nương và không được lẫn gạo tẻ. Đường để làm nhân bánh cũng phải lựa chọn rất cẩn thận, phải chọn đường phên có màu vàng, ngọt và không có sạn.\n" +
                    "\n" +
                    " \n" +
                    "\n" +
                    "Lá ngải rửa sạch, đun trong nước tro bếp từ 2 đến 3 giờ. Để có nước tro tốt, người ta chọn tro sạch, tốt nhất là tro tre nứa, hoặc tro vỏ đậu xanh. Tro sạch được lèn vào rá tre, để rá trên chậu tạo khoảng cách cho nước từ rá chảy xuống. Người ta đổ nước từ từ vào tro cho ngấm dần rồi chảy xuống chậu. Nước tro lúc đầu đặc có màu cà phê, sau loãng dần. Lá ngải đun trong nước tro rất chóng nhừ. Sau khi đun nhừ, đổ lá ngải ra rá, rửa nhiều lần cho sạch nước tro, nhặt bỏ sơ (gân lá, cuống lá già), vắt kiệt nước rồi nắm thành từng nắm bằng nắm tay.","Gạo làm bánh được ngâm từ tối hôm trước rồi đem đồ chín thành xôi vừa độ dẻo. Trong quá trình đồ, khi lên hơi, người ta thường tưới thêm lần nước để khi giã bánh sẽ dẻo hơn. \n" +
                    "\n" +
                    " \n" +
                    "\n" +
                    "Trong khi chờ xôi chín sẽ chuẩn bị nhân bánh, người ta đun đường phên lên thành mật sau đó trộn mật với vừng đen rang chín giã nhỏ. Nhân bánh chính là bí quyết tạo ra hương vị thơm ngon cho chiếc bánh. Xôi đồ chín giã ngay lúc còn nóng cùng với lá ngải để bánh mềm, mịn và dẻo. Sau khi xôi giã nhuyễn, các bà, các mẹ sẽ nhanh tay múc ra mâm để nặn bánh. Bánh được nặn thành hình tròn sau đó ấn dẹt ra, cho thìa nhân vào giữa, rồi gói vỏ bánh lại bọc kín lớp nhân bên trong thành hình như chiếc bánh dày là được. \n" +
                    "\n" +
                    " \n" +
                    "\n" +
                    "Bánh ngải dễ ăn, mát và không ngấy. Vị hăng hăng, thơm thơm là lạ của lá ngải như dung hòa cái dẻo, cái ngọt của nếp, của đường, miếng bánh có sự tươi non của đồi nương, cái hoang dã của lá rừng như gói cả mùa xuân trong mát.","banh_ngai","banh_ngai_2","banh_ngai_3","denduom");
        }
        db.close();

    }
    public List<dataFood> getdata(){
        List<dataFood> data=new ArrayList<>();
        DB db = new DB(context);
        db.open();
        if(db.checkCount()>0){
            data=db.getFood();
        }
        db.close();
        return data;
    }
}
